# asyncio_crash_in_second_run
example to reproduce a crash with asyncio in a second run of an embedded python interpreter
